package org.mfusco;

import org.mfusco.Applicant

global java.util.List answers;

rule CheckAge when
	$p: Applicant( age < 18 )
then
	answers.add($p.getFullName() + " is too young");
end

rule CheckDeath when
	$p: Applicant( death > 1 )
then
	answers.add("The deceased died more than one year ago");
end

// The deceased's death was COVID-19 related
// The deceased died in the U.S.
// The deceased died after May 20th, 2020
// You are a U.S. citizen or eligible non-citizen
// You paid for funeral or burial expenses and were not reimbursed
