package org.mfusco;

import org.mfusco.Applicant
import org.mfusco.BenefitMetaData
import java.sql.Date;

global java.util.List answers;

// The deceased's death was COVID-19 related
// The deceased died in the U.S.
// The deceased died after May 20th, 2020
// You are a U.S. citizen or eligible non-citizen
// You paid for funeral or burial expenses and were not reimbursed

rule CheckCovid when
	$p: Applicant( $p.(deceasedDiedFromCovid) == false )
then
	answers.add( "The deceased's death was not COVID-19 related." );
end

rule CheckDeathLocation when
	$p: Applicant( $p.deceasedDiedInUs() == false )
then
	answers.add( "The deceased did not die in the U.S." );
end

rule CheckDateOfDeath when
	$p: Applicant( Date.valueOf($p.deceasedDateOfDeath) < Date.valueOf("2020-05-20") )
then
	answers.add( "The deceased died before May 20th, 2020." );
end

rule CheckCitizenshipStatus when
	$p: Applicant( $p.applicantCitizenStatus() == false )
then
	answers.add( "The applicant is not a U.S. citizen." );
end

rule CheckFuneralExpenses when
	$p: Applicant( $p.applicantPaidFuneralExpenses() == true &&  applicantReimbursedFuneralExpenses() == true)
then
	answers.add( "The applicant Paid for funeral expenses, but allready got reimbursed." );
end
