package org.mfusco;

import org.mfusco.Applicant
import java.sql.Date;

global java.util.List answers;

// The deceased worked and paid Social Security taxes
// The deceased died within the last two years
// You are a U.S. citizen or eligible non-citizen
// Your relationship to the deceased is: spouse or child

rule LumpSumCheckSocialSecurity when
	$p: Applicant($p.deceasedPaidSocialSecurityTaxes() == false)
then
	answers.add( "The deceased did not pay Social Security taxes." );
end

rule LumpSumCheckDeath when
	$p: Applicant(death > 2)
then
	answers.add( "The deceased death was not within the last two years." );
end

rule LumpSumCheckCitizenshipStatus when
	$p: Applicant($p.applicantCitizenStatus() == false)
then
	answers.add( "The applicant is not a U.S. citizen." );
end

rule LumpSumCheckRelationship when
	$p: Applicant( getApplicantRelationshipToDeceased(new String[] {"Spouse", "Child"}) == false )

then
	answers.add( "The applicant has neither a spouse or child relationship to the deceased." );
end
